### ISSUE TITLE
Timeline graphs not updated with dates after ?

### ISSUE THREAD

**Issue by liquidat** [favstats/uaconflict_equipmentloss#1]
The timeline graphs have a **_"Last updated"_** timestamp saying 2022-04-12, however, the x-axis of the graphs only extends to the week of 2022-03-31. Looks like the graphs were not updated to stretch to the last week.

See for example this graph: https://github.com/favstats/uaconflict_equipmentloss/blob/main/img/overall_losses_time.png

**Comment by favstats** [comment]
The timeline graphs are working as intended. I always leave out the current week (which in this case is the week of April 7th, or the 7th week after the war began). Starting Friday, April 15th, you will see that the graph will have losses for Week 7.

**Comment by liquidat** [comment]
@favstats Ah, understood - I didn't realize that your week count started on a Friday, that explains my confusion.

Sorry for the noise, and thanks for the clarification!
