### ISSUE TITLE
Artillery losses over time by artillery types

### ISSUE THREAD

**Issue by tbertels** [favstats/uaconflict_equipmentloss#4]
It would be great to have an additional image with artillery losses over time by artillery types, like the one for vehicle losses.

**Comment by favstats** [comment]
hope this is useful:
https://github.com/favstats/uaconflict_equipmentloss#artillery-losses-over-time

**Comment by tbertels** [comment]
Nice, thanks!

Would it be possible to also include Multiple Rocket Launchers in this image?
They seem to be counted as artillery in https://github.com/favstats/uaconflict_equipmentloss/blob/main/dataviz.R#L484 but I don't know if it's already counted as self-propelled artillery.

**Comment by tbertels** [comment]
Wow, that was fast!
Thanks again!
Your work is very useful for analysis like this one: https://youtu.be/I98yqGR7yW4?t=116
